src/Entity/Blog.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BlogRepository")
 * @Vich\Uploadable
 */
class Blog
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="string", length=180, nullable=true)
     */
    private $subTitle;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\CategoryBlog", inversedBy="blogs")
     */
    private $CategoryBlog;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="BlogUser")
     */
    private $user;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @var File|null
     * 
     * @Vich\UploadableField(mapping="imag_ad", fileNameProperty="image")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="integer")
     */
    private $counter;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Coments", mappedBy="blog", orphanRemoval=true)
     */
    private $coments;

    /**
     * Undocumented function
     *
     * @param File|null $imageFile
     * 
     */
    public function setImageFile(?File $imageFile)
    {
        $this->imageFile = $imageFile;
        // on verifie que  c'est bien une instance de UploadedFile si c'est le cas on met à jours
        if ($this->imageFile instanceof UploadedFile ) {
            // on met à jours le champ update
            $this->updatedAt = new \DateTime('now');
        }

        return $this;
    }

    /**
     * Undocumented function
     *
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->coments = new ArrayCollection(); 
        // si il y a une création d'un article
        if($this->createdAt){
            // je met par défault le counter à 0
            $this->counter = 0;
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return(new Slugify())->slugify($this->title);
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getSubTitle(): ?string
    {
        return $this->subTitle;
    }

    public function setSubTitle(?string $subTitle): self
    {
        $this->subTitle = $subTitle;

        return $this;
    }

    public function getCategoryBlog(): ?CategoryBlog
    {
        return $this->CategoryBlog;
    }

    public function setCategoryBlog(?CategoryBlog $CategoryBlog): self
    {
        $this->CategoryBlog = $CategoryBlog;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image)
    {

            $this->image = $image;
        
        return $this;
    }

    public function getCounter(): ?int
    {
        return $this->counter;
    }

    public function setCounter(int $counter): self
    {
        $this->counter = $counter;

        return $this;
    }

    /**
     * @return Collection|Coments[]
     */
    public function getComents(): Collection
    {
        return $this->coments;
    }

    public function addComent(Coments $coment): self
    {
        if (!$this->coments->contains($coment)) {
            $this->coments[] = $coment;
            $coment->setBlog($this);
        }

        return $this;
    }

    public function removeComent(Coments $coment): self
    {
        if ($this->coments->contains($coment)) {
            $this->coments->removeElement($coment);
            // set the owning side to null (unless already changed)
            if ($coment->getBlog() === $this) {
                $coment->setBlog(null);
            }
        }

        return $this;
    }

}

src/Form/BlogType.php
<?php

namespace App\Form;

use App\Entity\Blog;
use App\Entity\CategoryBlog;
use Symfony\Component\Form\AbstractType;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class BlogType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class,  ['label' => 'titre'])
            ->add('imageFile', FileType::class, ['required' => false, 'label' => 'Image du blog', 'attr'=>['onchange'=>'readURL(this);']])
            ->add('subTitle', TextType::class,  ['label' => 'sous-titre', 'required' => false])
            ->add('CategoryBlog', EntityType::class, array(
                'class'        => CategoryBlog::class,
                'choice_label' => 'title',
                'multiple'     => false,
                'label' => 'categorie'
            ))
            ->add('content', CKEditorType::class, array(
                'attr' => array('class' => 'tinymce'),
                'label' => 'contenu'
        
            ))
            
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Blog::class,
        ]);
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Blog;
use App\Form\BlogType;
use App\Entity\Coments;
use App\Form\CommentType;
use App\Entity\CategoryBlog;
use App\Repository\BlogRepository;
use App\Repository\UserRepository;
use App\Repository\CategoryBlogRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Knp\Component\Pager\PaginatorInterface;

/**
 * @Route("/blog")
 */
class BlogController extends AbstractController
{


    /**
     * @Route("/admin/", name="admin_blog_index", methods="GET")
     * 
     * Liste tout les blogs pour l'admin
     */
    public function index(Request $request, PaginatorInterface $paginator,BlogRepository $blogRepository, UserRepository $userRepo): Response
    {
        $page = $paginator->paginate(
            $blogRepository->findBy([],['createdAt'=> 'desc']),
            $request->query->getInt('page', 1),
            12
    
        );
        return $this->render(
            'admin/blog/index.html.twig',
            [
                'blogs' => $page,
                'user' => $userRepo->findAll()
            ]
        );
    }

    /**
     * @Route("/admin/new", name="admin_blog_new", methods="GET|POST")
     * 
     * Ajoute un nouveau blog
     * 
     */
    public function new(Request $request)
    {
        // initialisation du nouveau blog
        $blog = new Blog();
        //appelle du formulaire qui contient les informations du blog je lui met l'entité dans le parametre
        $form = $this->createForm(BlogType::class, $blog);
        $form->handleRequest($request);

        // verification du formulaire si il est soumis et si il est valide
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            //ajout de l'utilisateur qui ajoute le blog
            $blog->setUser($this->getUser());
            // je persist les données avant de les envoyer
            $em->persist($blog);
            //j'envois toute les données transmise 
            $em->flush();
            // je redirige l'utilisateur à la liste de tout les blogs
            return $this->redirectToRoute('admin_blog_index');
        }
        // je transmet le formulaire et l'entitée à la vue
        return $this->render('admin/blog/new.html.twig', [
            'blog' => $blog,
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/{slug}-{id}", name="blog_show", methods="GET|POST", requirements={"slug": "[a-z0-9\-]*", "id": "[0-9]*"})
     * 
     */
    public function show(Blog $blog, Request $request, UserRepository $userRepo, CategoryBlogRepository $blogCategories)
    {

        // récuperation de toutes les categories des blogs
        $categories = $blogCategories->findAll();
        // recuperation de tout les utilisateurs
        $user = $userRepo->findAll();

        // initialisation de l'entité Coments qui permet de traiter le formulaire des commentaire
        $comment = new Coments();
        //déclaration du formulaire pour les commentaires
        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);
        // si les informations du formulaire sont soumis et valide
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            // je transmet la date à aujourd'hui et je transmet le blog pour le lié 
            $comment->setCreatedAt(new \DateTime())
                ->setBlog($blog);
            // persist les données        
            $em->persist($comment);
            // transmet les données à la base de donnée
            $em->flush();

            // redirection sur le blog en cour
            return $this->redirectToRoute('blog_show', ['id' => $blog->getId()]);
        }

        // renvoie le formulaire , les categories et les users à la vue
        return $this->render('blog/show.html.twig', [
            'blog' => $blog,
            'form' => $form->createView(),
            'categories' => $categories,
            'user' => $user

        ]);
    }

    /**
     * @Route("/admin/{id}/edit", name="admin_blog_edit", methods="GET|POST")
     */
    public function edit(Request $request, Blog $blog): Response
    {
        $form = $this->createForm(BlogType::class, $blog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_blog_index', ['id' => $blog->getId()]);
        }

        return $this->render('admin/blog/edit.html.twig', [
            'blog' => $blog,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/admin/{id}", name="admin_blog_delete", methods="DELETE")
     */
    public function delete(Request $request, Blog $blog): Response
    {
        if ($this->isCsrfTokenValid('delete' . $blog->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($blog);
            $em->flush();
        }

        return $this->redirectToRoute('admin_blog_index');
    }

    /**
     * @Route("/", name="blog_public_index", methods="GET")
     * renvoie tout les blog pour la vue public
     */
    public function public_index(PaginatorInterface $paginator, BlogRepository $blogRepository, UserRepository $userRepo, CategoryBlogRepository $blogCategories, Request $request): Response
    {

        $page = $paginator->paginate(
            $blogRepository->findBy([],['createdAt'=> 'desc']),
            $request->query->getInt('page', 1),
            12
    
        );
        return $this->render(
            'blog/public_show_index.html.twig',
            [
                //'blogs' => $blogRepository->findAll(),
                'blogs'=> $page,
                'categories' => $blogCategories->findAll(),
                'user' => $userRepo->findAll()
            ]
        );
    }

    /**
     * @Route("/category/{id}", name="blog_categorie_index", methods="GET")
     * renvoi toute les catgories
     */
    public function public_category_index(BlogRepository $blogRepository, CategoryBlog $id, CategoryBlogRepository $blogCategories): Response
    {

        return $this->render(
            'blog/category_public_show_index.html.twig',
            [
                'blogs' => $blogRepository->findBy(['CategoryBlog' => $id]),
                'categories' => $blogCategories->findAll(),
            ]
        );
    }

    /**
     * @Route("/counter/{id}", name="blog_count", methods="GET")
     * Ajoute une vue pour le blog
     */
    public function counter(Blog $blog)
    {

        $em = $this->getDoctrine()->getManager();
        // récuperer la valeur contenu dans la base de donnée puis je lui ajoute 1 
        $val = $blog->getCounter() + 1;
        // je set le nouveau résultat dans la base de donnée
        $blog->setCounter($val);
        //puis je transmet
        $em->flush();

        return $this->redirectToRoute('blog_index');
    }
}

templates/blog/category_public_show_index.html.twig
{% extends 'blog/public_show_index.html.twig' %}

    {% block blog %}
    <section class="container">
        <section class="post-content-area">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 posts-list">
                        {% for blog in blogs %}
                            <div class="single-post row mb-5">
                                <div class="col-lg-3  col-md-3 meta-details">
                                    <ul class="tags">
                                        <li>
                                            <a href="#">Food,</a>
                                        </li>
                                        <li>
                                            <a href="#">Technology,</a>
                                        </li>
                                        <li>
                                            <a href="#">Politics,</a>
                                        </li>
                                        <li>
                                            <a href="#">Lifestyle</a>
                                        </li>
                                    </ul>
                                    <div class="user-details row">
                                        <p class="user-name col-lg-12 col-md-12 col-6">
                                            <a href="#">Mark wiens</a>
                                            <span class="lnr lnr-user"></span></p>
                                        <p class="date col-lg-12 col-md-12 col-6">
                                            <a href="#">
                                                {{ blog.createdAt | date('d/m/y') }}
                                            </a>
                                            <span class="lnr lnr-calendar-full"></span></p>
                                        <p class="view col-lg-12 col-md-12 col-6">
                                            <a href="#">{{ blog.counter }} Views</a>
                                            <span class="lnr lnr-eye"></span></p>
                                        <p class="comments col-lg-12 col-md-12 col-6">
                                            <a href="#">{{ blog.coments|length }} Commentaires</a>
                                            <span class="lnr lnr-bubble"></span></p>
                                    </div>
                                </div>
                                <div class="col-lg-9 col-md-9 ">
                                    <div class="feature-img">
                                        <img src="{{ vich_uploader_asset(blog, 'imageFile') }}" class="" alt="" width="100" height="">

                                    </div>
                                    <a class="posts-title" href="{{ path('blog_show', {'id': blog.id, 'slug': blog.slug}) }}">
                                        <h3>{{ blog.title }}</h3>
                                    </a>
                                    <p class="excert">
                                        {{ blog.content | slice(0,200) | raw }}
                                    </p>
                                    <a href=" {{ path('blog_show', {'id': blog.id, 'slug': blog.slug}) }} " class="primary-btn">Lire plus</a>
                                </div>
							
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

templates/blog/public_show_index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Blog{% endblock %}

{% block slide %} 
<!-- start banner Area -->
           
            <!-- End banner Area -->
{% endblock %}

{% block body %}
<link href=" {{ asset('css/pagination.css') }} " rel="stylesheet">

        <!-- Start top-category-widget Area -->
<section class="top-category-widget-area pt-90 pb-90 ">
	<div class="container">
        <div class="row">	
            {% for categorie in categories %}	
                <div class="col-lg-4 " >
					<div class="single-cat-widget">
						<div class="content relative">
							<div class="overlay overlay-bg"></div>
								<a href=" {{ path('blog_categorie_index', {'id': categorie.id}) }} ">
								    <div class="thumb">
								  		<img class="content-image img-fluid d-block mx-auto" src="{{ vich_uploader_asset(categorie, 'imageFile') }}" alt="">
								  	</div>
								    <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase"> {{categorie.title}} </h4>
								        <span></span>								        
								        <p>{{categorie.description}}</p>
								    </div>
								</a>
						</div>
					</div>
                </div>
            {% endfor %}							
		</div>
	</div>	
</section>
			<!-- End top-category-widget Area -->
{% block blog %}
    <section class="container">
        <section class="post-content-area">
            <div class="container">
               <!-- <div class="row"> -->
                    <div class="row d-flex justify-content-around posts-list">
                        {% for blog in blogs %}
                            <div class="col-s-12 col-sm-12 col-md-6 single-post row mb-5">
                                <div class="col-lg-3  col-md-3 meta-details">
                                    <ul class="tags">
                                        <li>
                                           <a href="#">{{ blog.categoryBlog.title }}</a>
                                        </li>
                                    </ul>
                                    <div class="user-details row">
                                        <p class="user-name col-lg-12 col-md-12 col-6">
                                            <a href="#"> {% if blog.user %}{{blog.user.username}} {% else %} Wanagaine {% endif %}
                                             </a>
                                            <span class="lnr lnr-user"></span></p>
                                        <p class="date col-lg-12 col-md-12 col-6">
                                            <a href="#">
                                                {{ blog.createdAt | date('d/m/y') }}
                                            </a>
                                            <span class="lnr lnr-calendar-full"></span></p>
                                        <p class="view col-lg-12 col-md-12 col-6">
                                            <a href="#">{{ blog.counter }} Views</a>
                                            <span class="lnr lnr-eye"></span></p>
                                        <p class="comments col-lg-12 col-md-12 col-6">
                                            <a href="#">{{ blog.coments|length }} Commentaires</a>
                                            <span class="lnr lnr-bubble"></span></p>
                                    </div>
                                </div>
                                <div class="col-lg-9 col-md-9 ">
                                    <div class="feature-img">
                                        <img src="{{ vich_uploader_asset(blog, 'imageFile') }}" class="" alt="" width="100" height="">

                                    </div>
                                    <a class="posts-title" href="{{ path('blog_show', {'id': blog.id, 'slug': blog.slug}) }}">
                                        <h3>{{ blog.title }}</h3>
                                    </a>
                                    <p class="excert">
                                        {{ blog.content | slice(0,200) | raw }}
                                    </p>
                                    <a href=" {{ path('blog_show', {'id': blog.id, 'slug': blog.slug}) }} " class="primary-btn border border-danger">Lire plus</a>
                                </div>
							
                            </div>
                        {% endfor %}
                    </div>
               <!-- </div> -->
            </div>
            <div class="row">
                <div class="pagination mb-5 ml-auto mr-auto text-purple">
                {{ knp_pagination_render(blogs)}}
                </div>
            </div>
        </section>
       
    </section>
    {% endblock %}
{% endblock %}

templates/blog/show.html.twig
{% extends '/blog/public_show_index.html.twig' %}

{% block title %}{{ blog.title }}{% endblock %}

{% block blog %}



    <script>
        function addVue() {
            // utilisation du setTimeout initialisation qui se déclenche à 4 secondes  
            setTimeout(function () {
                $.ajax({
                    //appelle l'url qui contient la function d'incrémentation de vue
                    url: "{{ path('blog_count', {'id': blog.id}) }}", type: 'GET', 
                });
            }, 4000);
        }

        $(document).ready(function () {
            addVue();
        });

        (function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
        
    </script>
<head>
  <title>wanagaine</title>
  <meta property="og:url"           content="{{ url('blog_show', {'id': blog.id, 'slug': blog.slug}) }}" />
  <meta property="og:type"          content="website" />
  <meta property="og:title"         content="{{blog.title}}" />
  <meta property="og:description"   content="{{blog.content | slice(0,200) | raw }}" />
  <meta property="og:image"         content="{{absolute_url(vich_uploader_asset(blog, 'imageFile')) }}" />
  <meta property="og:locale"        content="fr_FR" />
</head>
 
    <section class="post-content-area p-5">
        <div class="container">
            <div class="text-center">
            
                <h1>{{ blog.title }}</h1>
                
            </div>
            <div class="row">

                <div class="col-lg-8 posts-list">
                
                    <div class="single-post row">

                        <div class="col-lg-3  col-md-3 meta-details">
                            <ul class="tags">
                                <li>
                                    <a href="#">Food,</a>
                                </li>
                                <li>
                                    <a href="#">Technology,</a>
                                </li>
                                <li>
                                    <a href="#">Politics,</a>
                                </li>
                                <li>
                                    <a href="#">Lifestyle</a>
                                </li>
                                 <div id="fb-root"></div>
                            <div class="fb-share-button" 
                                data-href="{{ url('blog_show', {'id': blog.id, 'slug': blog.slug}) }}" 
                                data-layout="button_count">
                            </div>
                            </ul>
                            <div class="user-details row">
                                <p class="user-name col-lg-12 col-md-12 col-6">
                                
                                    <a href="#"> {% if blog.user == null %}Wanagaine{% else %} {{blog.user.username}}{% endif %} </a>
                                    <span class="lnr lnr-user"></span></p>
                                <p class="date col-lg-12 col-md-12 col-6">
                                    <a href="#">
                                        {{ blog.createdAt | date('d/m/y') }}
                                    </a>
                                    <span class="lnr lnr-calendar-full"></span></p>
                                <p class="view col-lg-12 col-md-12 col-6">
                                    <a href="#">
                                        {{ blog.counter }}
                                        Views</a>
                                    <span class="lnr lnr-eye"></span></p>
                                <p class="comments col-lg-12 col-md-12 col-6">
                                    <a href="#">{{ blog.coments|length }}
                                        Comments</a>
                                    <span class="lnr lnr-bubble"></span></p>
                            </div>

                        </div>
                        <div class="col-lg-9 col-md-9 ">
                            <div class="feature-img">
                                <img src="{{ vich_uploader_asset(blog, 'imageFile') }}" alt="">
                            </div>
                            <h3>{{ blog.title }}</h3>
                            <p class="excert">
                                {{ blog.content | raw }}
                            </p>
                            {% if is_granted('ROLE_ADMIN') %}
                                <div class="row p-2">
                                    <a class=" btn btn-primary" href="{{ path('admin_blog_edit', {'id': blog.id}) }}">modifier</a>

                                    {{ include('admin/blog/_delete_form.html.twig') }}
                                </div>
                            {% endif %}

                            <div class="comments-area">
								<h4>{{ blog.coments|length }} Commentaires</h4>
                                {% for comment in blog.coments %}
                                <pre>
                                    {{ dump(comment) }}
                                </pre>
								<div class="comment-list">
                                    <div class="single-comment justify-content-between d-flex">
                                        <div class="user justify-content-between d-flex">
                                            <div class="thumb">
                                                <img src="img/blog/c1.jpg" alt="">
                                            </div>
                                            <div class="desc">
                                                <h5><a href="#">{{ comment.author }}</a></h5>
                                                <p class="date">{{ comment.createdAt | date('d/M/Y') }} à {{ comment.createdAt | date('H:i:s') }}  </p>
                                                <p class="comment">
                                                    {{comment.content}}
                                                </p>
                                            </div>
                                        </div>
    
                                    </div>
                                </div>
                                {% endfor %}

                                <div class="comment-form">
								<h4>Laisser un commentaire</h4>
								{{ form_start(form) }}
									<div class="form-group form-inline">
									  <div class="form-group col-lg-6 col-md-12 name">
                                      {% if app.user %}
                                        {{ form_widget(form.author, {'attr': {'value': app.user.username }})}}
                                      {% else %}
                                        {{ form_widget(form.author)}}
									  {% endif %}
                                      </div>
									</div>
									<div class="form-group">
								         {{ form_widget(form.content) }}
                                    </div>
								    <button class="primary-btn text-uppercase">{{ button_label|default('Commenter') }}</button>
								 {{ form_end(form) }}
							</div>
                            </div>
                        </div>
                            
                        <div class="mt-2 mb-5">

                        </div>
                    </div>

                </div>
            </div>
            <a class="btn btn-secondary" href="{{ path('blog_public_index') }}">Retour</a>

        </div>

    </section>

{% endblock %}